import "./globals.css";
import Header from "@/components/layout/Header";
import MobileNavbar from "@/components/layout/MobileNavbar";

export const metadata = {
  title: "Online Shop Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MobileNavbar />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
