import "./globals.css";
import "@splidejs/react-splide/css";
import Header from "@/components/layout/Header";
import MobileNavbar from "@/components/layout/MobileNavbar";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Online Shop Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <Toaster position="top-center" />
        </div>
        <MobileNavbar />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
